apiVersion: v1
kind: Service
metadata:
  name: redisq
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    
---

apiVersion: v1
kind: Endpoints
metadata:
  name: redisq
subsets:
  - addresses:
      - ip: "192.168.1.71"
    ports:
      - port: 6379