apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - image: controller
        name: controller
        imagePullPolicy: IfNotPresent
        command: ["python3", "serve.py"]
        env:
        - name: RUNTIME_ENV
          value: "local"
        ports:
        - containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          tcpSocket:
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
        
---

apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    app: controller
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 6000
    targetPort: 8000
  selector:
    app: controller
    
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controller
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: controller
            port:
              number: 8000