apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    
---

apiVersion: v1
kind: Endpoints
metadata:
  name: db
subsets:
  - addresses:
      - ip: "192.168.1.71"
    ports:
      - port: 3003
      
---

apiVersion: v1
kind: Service
metadata:
  name: model-6001
spec:
  ports:
  - port: 6001
    targetPort: 6001
    protocol: TCP
    
---

apiVersion: v1
kind: Endpoints
metadata:
  name: model-6001
subsets:
  - addresses:
      - ip: "192.168.1.71"
    ports:
      - port: 6001
      
---

apiVersion: v1
kind: Service
metadata:
  name: model-6002
spec:
  ports:
  - port: 6002
    targetPort: 6002
    protocol: TCP
    
---

apiVersion: v1
kind: Endpoints
metadata:
  name: model-6002
subsets:
  - addresses:
      - ip: "192.168.1.71"
    ports:
      - port: 6002