apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    
---

apiVersion: v1
kind: Endpoints
metadata:
  name: db
subsets:
  - addresses:
      - ip: "192.168.1.71"
    ports:
      - port: 3003

---

apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    
---

apiVersion: v1
kind: Endpoints
metadata:
  name: cache
subsets:
  - addresses:
      - ip: "192.168.1.71"
    ports:
      - port: 3002
      
---

apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    
---

apiVersion: v1
kind: Endpoints
metadata:
  name: queue
subsets:
  - addresses:
      - ip: "192.168.1.71"
    ports:
      - port: 3001